### PR TITLE
Add BUCK build configuration

### LINKED ISSUE #5: Buck build script
In order to stay current with the way Gerrit is headed, a Buck build script should be written to replace Maven.

### PR DESCRIPTION
**Pull request by dpursehouse**
Closes #5

Change-Id: Ia866a3de9769e2f5e27209df63ec4cf394f29338

### CODE REVIEW

**Comment by nllptr** [comment]
I'm really eager to merge this one, however I have a problem. Building in the Gerrit tree works fine, it's building standalone that I can't get to work. Buck says that it can't get the dependency '//lib:gson'. I've tried reading up on Buck, but I can't pinpoint the issue. Thanks for contributing!

**Comment by dpursehouse** [comment]
Maybe need to add the bucklets link.  I'll look into it on Monday.

**Comment by dpursehouse** [comment]
I added some more config and now it also works in standalone mode.  Please try again.

**Comment by nllptr** [comment]
:+1:

**Pull request merged**
