### PR TITLE
Always add reviewers as the change owner

### LINKED ISSUE #23: Access to static field from instance method
The following code in ReviewAssistant.java:

```
//TODO Move into addReviewers?
realUser = true;
addReviewers(change, finalMap);
realUser = false;
```

causes a warning from FindBugs:

> Write to static field com.github.reviewassistant.reviewassistant.ReviewAssistant.realUser from instance method com.github.reviewassistant.reviewassistant.ReviewAssistant.run()
> 
> This instance method writes to a static field. This is tricky to get correct if multiple instances are being manipulated, and generally bad practice.

The only other place it's used is in ChangeEventListener:

```
@Override public CurrentUser getCurrentUser() {
  if (!ReviewAssistant.realUser) {
    return pluginUser;
  } else {
    return identifiedUserFactory.create(change.getOwner());
  }
}
```

I don't think this is going to work as expected when there are multiple instances of the ReviewAssistant object, but at the moment I don't have a better solution.

### PR DESCRIPTION
**Pull request by dpursehouse**
Fixes #23

Change-Id: I2df051319e5eedae74773167e0eff23bf83d588c

### CODE REVIEW

**Comment by williamphan** [comment]
Hi David,

Thanks for helping out! 
I can't test this right now, but it did not work for adding reviewers last time I tried, it was however against 2.10-rc0. Does it work with the current build? 

Cheers!

**Comment by dpursehouse** [comment]
@williamphan I haven't actually tested it fully yet, however the implementation now is the same as it is in the reviewers plugin.

I'll try to find time to test during this week.

**Comment by williamphan** [comment]
@dpursehouse Thanks! From what I've observed, if my memory serves me right, "changeOwner" could fetch the required information about a change but could not add reviewers, vice versa for "pluginUser".

**Comment by dpursehouse** [comment]
@davido have you seen this problem with the reviewers or reviewers-by-blame project?  The changes I've made in this commit make the implementation same as those plugins.

**Comment by davido** [comment]
No, I havn't. Why shouldn't change owner be able to add a reviewer?

**Comment by dpursehouse** [comment]
Moving this to gerrit-review.

**Pull request closed without merging**
